import type { HelpIssue } from './types'

export const helpIssues: HelpIssue[] = [
  {
    id: 'no-arranca',
    title: 'La furgo no arranca',
    icon: 'car',
    severity: 'urgent',
    relatedGuideId: 'electricidad',
    placeholder: true,
    editorNote: 'Añadir particularidades: antipinzamiento, botón de arranque, etc.',
    steps: [
      'Confirma que está en punto muerto o parking, y el embrague pisado si pide arranque en marcha.',
      'Mira si el mando desbloquea las puertas: si no hay luces de cabina, puede ser la batería de arranque.',
      'No insistas más de 8–10 segundos seguidos. Espera y prueba otra vez.',
      'Si huele a quemado o sale un testigo rojo, para y contacta.',
    ],
  },
  {
    id: 'no-electricidad',
    title: 'No tengo electricidad',
    icon: 'power',
    severity: 'normal',
    relatedGuideId: 'electricidad',
    placeholder: true,
    steps: [
      'Comprueba el nivel de batería auxiliar en el panel.',
      'Comprueba que el interruptor principal esté encendido.',
      'Comprueba que no haya saltado ningún fusible (caja de ejemplo bajo el asiento).',
      'Prueba una sola luz. Si esa funciona y el USB no, puede ser solo ese circuito.',
    ],
  },
  {
    id: 'no-agua',
    title: 'No sale agua',
    icon: 'water',
    severity: 'normal',
    relatedGuideId: 'agua',
    placeholder: true,
    steps: [
      'Mira el nivel del depósito de agua limpia.',
      'Enciende la bomba y escucha si zumba.',
      'Si zumba sin parar y no sale nada, apágala: puede estar en seco.',
      'Abre el grifo de la cocina, no solo la ducha, para ver si el problema es la manguera.',
    ],
  },
  {
    id: 'no-ducha',
    title: 'No funciona la ducha',
    icon: 'shower',
    severity: 'normal',
    relatedGuideId: 'ducha',
    placeholder: true,
    steps: [
      'Confirma que hay agua y que la bomba está encendida.',
      'Revisa que la manguera esté bien encajada y sin pliegues.',
      'Prueba el grifo interior: si ese sí funciona, el fallo está en la ducha.',
    ],
  },
  {
    id: 'nevera',
    title: 'La nevera no enfría',
    icon: 'fridge',
    severity: 'normal',
    relatedGuideId: 'nevera',
    placeholder: true,
    steps: [
      'Mira si el piloto está encendido y en qué nivel.',
      'Comprueba batería auxiliar e interruptor principal.',
      'No la abras cada dos minutos: tarda en recuperar.',
      'Si lleva horas y sigue caliente, contacta antes de que se estropee la comida.',
    ],
  },
  {
    id: 'calefaccion',
    title: 'No funciona la calefacción',
    icon: 'heat',
    severity: 'normal',
    relatedGuideId: 'calefaccion',
    placeholder: true,
    steps: [
      'Mantén el encendido dos segundos y espera a que sople.',
      'Comprueba que hay combustible en el depósito del vehículo.',
      'Mira la batería auxiliar.',
      'Si parpadea un código en el mando, anótalo o fotografía y escríbenos.',
    ],
  },
  {
    id: 'puerta',
    title: 'No puedo abrir una puerta',
    icon: 'doors',
    severity: 'normal',
    relatedGuideId: 'puertas',
    placeholder: true,
    steps: [
      'Prueba mando y llave física. Acércate a la puerta.',
      'Busca un seguro interior o un giratorio en el marco.',
      'No fuerces: un portón trabado se tuerce fácil.',
      'Si estás fuera y no entra nadie, contacta.',
    ],
  },
  {
    id: 'testigo',
    title: 'Se ha encendido un testigo',
    icon: 'warning',
    severity: 'urgent',
    placeholder: true,
    editorNote: 'Añadir foto del cuadro y qué testigos son normales (AdBlue, etc.).',
    steps: [
      'Para en un sitio seguro y fotografía el cuadro.',
      'Rojo o con un icono de aceite/temperatura: no sigas. Contacta.',
      'Ámbar: anota si el coche va raro (pérdida de potencia, humo, ruido).',
      'No ignores un testigo de motor en un viaje largo.',
    ],
  },
  {
    id: 'pinchazo',
    title: 'He pinchado',
    icon: 'tire',
    severity: 'urgent',
    placeholder: true,
    editorNote: 'Indicar si hay rueda de recambio, kit antipinchazos o solo asistencia.',
    steps: [
      'Señaliza y sal del carril si puedes. Luces de emergencia.',
      'No circules con la rueda destrozada: dañas la llanta.',
      'Esta furgo: kit / recambio / solo asistencia — sustituir.',
      'Llama a asistencia en carretera y, si hace falta, al 112.',
    ],
  },
  {
    id: 'accidente',
    title: 'He tenido un accidente',
    icon: 'crash',
    severity: 'urgent',
    placeholder: true,
    steps: [
      'Primero las personas. Si hay heridos, llama al 112.',
      'Señaliza, chaleco si sales a la calzada, fotos de todo (matrículas, daños, vía).',
      'Rellena el parte amistoso (carpeta gris de la guantera, ejemplo).',
      'Avisa a asistencia y a nosotros cuando sea seguro.',
    ],
  },
  {
    id: 'llaves',
    title: 'He perdido las llaves',
    icon: 'key',
    severity: 'urgent',
    placeholder: true,
    steps: [
      'Revisa bolsillos, guantera, cajón de la cocina y el bolsillo de la corredera.',
      'Mira en el suelo junto a las puertas y bajo el felpudo exterior si lo hay.',
      'No intentes forzar una cerradura.',
      'Contacta: podemos orientar sobre duplicado o cerrajero.',
    ],
  },
  {
    id: 'otro',
    title: 'Otro problema',
    icon: 'help',
    severity: 'normal',
    placeholder: true,
    steps: [
      'Mira si encaja en alguna guía: puertas, agua, luz, gas, nevera.',
      'Haz una foto o un vídeo corto de lo que ocurre.',
      'Anota dónde estás y si podéis seguir viajando o no.',
      'Escríbenos o llama: mejor un mensaje claro que uno de prisa.',
    ],
  },
]

export function getHelpIssue(id: string): HelpIssue | undefined {
  return helpIssues.find((issue) => issue.id === id)
}
