import type { Situation } from './types'

export const situations: Situation[] = [
  {
    id: 'conducir',
    title: 'Voy a conducir',
    shortTitle: 'Conducir',
    description: 'Recoger, cerrar y comprobar antes de arrancar.',
    icon: 'drive',
    relatedGuideIds: ['antes-de-conducir', 'puertas', 'ventanas', 'exterior'],
    placeholder: true,
    editorNote: 'Alinear con el inventario real (toldo, mesa, ducha exterior…).',
    checklist: [
      { id: 'mesa', label: 'Recoger mesa interior y exterior' },
      { id: 'objetos', label: 'Guardar objetos sueltos' },
      { id: 'ventanas', label: 'Cerrar ventanas' },
      { id: 'claraboyas', label: 'Cerrar claraboyas' },
      { id: 'puertas', label: 'Comprobar puertas y portón' },
      { id: 'cama', label: 'Recoger la cama si hace falta' },
      { id: 'nevera', label: 'Comprobar que la nevera está bien cerrada' },
      { id: 'exterior', label: 'Desconectar manguera, cable, sillas y calzos' },
      { id: 'vuelta', label: 'Dar una vuelta alrededor de la furgo' },
    ],
  },
  {
    id: 'dormir',
    title: 'Voy a dormir',
    shortTitle: 'Dormir',
    description: 'Aparcar, montar la cama y dejar el interior agradable.',
    icon: 'sleep',
    relatedGuideIds: ['cama', 'ventanas', 'calefaccion', 'electricidad'],
    placeholder: true,
    checklist: [
      { id: 'aparcar', label: 'Aparcar en llano y echar el freno de mano' },
      { id: 'cama', label: 'Preparar la cama' },
      { id: 'oscuro', label: 'Colocar oscurecedores' },
      { id: 'aire', label: 'Dejar un poco de ventilación' },
      { id: 'calefaccion', label: 'Encender calefacción si hace falta' },
      { id: 'bateria', label: 'Comprobar la batería auxiliar' },
      { id: 'puertas', label: 'Cerrar y asegurar puertas' },
    ],
  },
  {
    id: 'cocinar',
    title: 'Voy a cocinar',
    shortTitle: 'Cocinar',
    description: 'Ventilar, usar el gas y dejarlo apagado y guardado.',
    icon: 'cook',
    relatedGuideIds: ['cocina', 'agua', 'ventanas'],
    placeholder: true,
    checklist: [
      { id: 'ventilar', label: 'Abrir ventana o puerta para ventilar' },
      { id: 'gas', label: 'Preparar el camping gas en superficie estable' },
      { id: 'uso', label: 'Encender, cocinar y no dejar el fogón solo' },
      { id: 'apagar', label: 'Apagar el gas del todo' },
      { id: 'guardar', label: 'Dejar enfriar y guardar el camping gas' },
    ],
  },
  {
    id: 'ducha',
    title: 'Voy a ducharme',
    shortTitle: 'Ducharme',
    description: 'Agua, ducha, recoger y no dejar la bomba encendida.',
    icon: 'shower',
    relatedGuideIds: ['ducha', 'agua'],
    placeholder: true,
    checklist: [
      { id: 'nivel', label: 'Comprobar que hay agua limpia' },
      { id: 'preparar', label: 'Preparar la ducha y la manguera' },
      { id: 'usar', label: 'Activar la bomba y ducharse' },
      { id: 'recoger', label: 'Apagar la bomba y recoger la ducha' },
      { id: 'grises', label: 'Tener en cuenta las aguas usadas' },
    ],
  },
  {
    id: 'electricidad',
    title: 'Necesito electricidad',
    shortTitle: 'Electricidad',
    description: 'Panel, batería, luces y qué hacer si no hay corriente.',
    icon: 'power',
    relatedGuideIds: ['electricidad'],
    placeholder: true,
    checklist: [
      { id: 'principal', label: 'Localizar y encender el interruptor principal' },
      { id: 'nivel', label: 'Mirar el nivel de la batería auxiliar' },
      { id: 'luces', label: 'Probar luces y USB' },
      { id: 'ahorro', label: 'Apagar lo que no haga falta' },
      {
        id: 'camping',
        label: 'Si hay toma de camping, conectar el cable (si aplica)',
        hint: 'Sustituir si esta furgo no usa cable de 220V.',
      },
    ],
  },
  {
    id: 'devolver',
    title: 'Voy a devolver la furgo',
    shortTitle: 'Devolver',
    description: 'La lista importante del último día. Sin prisas, casilla a casilla.',
    icon: 'return',
    relatedGuideIds: ['antes-de-conducir', 'nevera', 'agua', 'exterior'],
    placeholder: true,
    editorNote: 'Ajustar política de combustible, vaciado de aguas y fotos de devolución.',
    checklist: [
      { id: 'combustible', label: 'Llenar combustible al nivel acordado' },
      { id: 'aguas', label: 'Vaciar aguas si corresponde' },
      { id: 'basura', label: 'Retirar toda la basura' },
      { id: 'nevera', label: 'Vaciar y limpiar la nevera' },
      { id: 'accesorios', label: 'Guardar accesorios en su sitio' },
      { id: 'ventanas', label: 'Comprobar ventanas y claraboyas' },
      { id: 'puertas', label: 'Comprobar puertas y portón' },
      { id: 'mesa', label: 'Guardar mesa y sillas' },
      { id: 'fotos', label: 'Hacer fotos finales (interior, exterior, km)' },
      { id: 'llaves', label: 'Dejar las llaves donde os hayamos dicho' },
    ],
  },
]

export function getSituation(id: string): Situation | undefined {
  return situations.find((situation) => situation.id === id)
}
